apiVersion: v1
kind: ConfigMap
metadata:
  name: code-completion
  namespace: costrict
data:
  config.yaml: |
    codebaseContext:
      disableDefinitionSearch: true
      disableRelationSearch: true
      disableSemanticSearch: true
      codebaseDefinitionURL: "http://codebase-querier-svc.costrict.svc.cluster.local:8888/codebase-indexer/api/v1/search/definition"
      codebaseSemanticURL: "http://codebase-querier-svc.costrict.svc.cluster.local:8888/codebase-embedder/api/v1/search/semantic"
      codebaseRelationURL: "http://codebase-querier-svc.costrict.svc.cluster.local:8888/codebase-indexer/api/v1/search/relation"
      semanticTopK: 5
      semanticScoreThreshold: 0.5
      relationLayer: 3
      relationIncludeContent: false
      requestTimeout: 1000ms
      totalTimeout: 2000ms
    models:
      - completionsUrl: "${{__env_profile.completions_url}}"
        modelName: "${{__env_profile.model_name}}"
        authorization: "${{__env_profile.model_authorization}}"
        tags: 
          - fasttransformer
          - deepseek
        timeout: 3000ms
        maxPrefixContext: 4096
        maxSuffixContext: 1024
        maxOutputToken: 50
        fimBegin: "<｜fim▁begin｜>"
        fimEnd: "<｜fim▁end｜>"
        fimHole: "<｜fim▁hole｜>"
        fimStop: ["<｜end▁of▁sentence｜>", "<|EOT|>", "▁<MID>"]
        tokenizerPath: "bin/deepseek-tokenizer/tokenizer.json"
        maxConcurrent: ${{__env_profile.model_concurrent}}
        disablePrune: false
    streamController:
      maintainInterval: 600s
      completionTimeout: 4500ms
    completionsConfig:
      disableScore: true
      disableLanguageFeature: false
      thresholdScore: 0.3
      strPattern: ".*"
      treePattern: ".*"
      lineCountThreshold: 100
      endTag: "</completion>"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: code-completion
  namespace: costrict
  labels:
    app.kubernetes.io/name: code-completion
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: code-completion
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: code-completion
        app.kubernetes.io/name: code-completion
    spec:
      containers:
      - image: ${{SHENMA_DOCKER_REPO}}/code-completion:${{IMAGE_TIMESTAMP}}
        imagePullPolicy: IfNotPresent
        name: code-completion
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          limits:
            cpu: 2
            memory: 2Gi
          requests:
            cpu: 1
            memory: 1Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
          - mountPath: /app/config.yaml
            name: config-volume
            subPath: config.yaml
      volumes:
        - configMap:
            defaultMode: 420
            name: code-completion
          name: config-volume
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  namespace: costrict
  name: code-completion
  labels:
    app: code-completion
    app.kubernetes.io/name: code-completion
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: code-completion
