# 代码库上下文配置
codebaseContext:
  # 上下文检索url
  codebaseDefinitionURL: "http://localhost:8080/api/v1/codebase/definition"
  codebaseSemanticURL: "http://localhost:8080/api/v1/codebase/semantic"
  codebaseRelationURL: "http://localhost:8080/api/v1/codebase/relation"
  # 语义检索参数
  semanticTopK: 10
  semanticScoreThreshold: 0.7
  # 请求超时
  requestTimeout: 30s
  # 禁用项目
  disEnableDefinitionSearch: false
  disEnableSemanticSearch: false
  # 耗时
  contextCostTime: 10s

# 模型配置
models:
  - completionsUrl: "http://172.25.208.1:59999/v1/completions"
    modelName: "DeepSeek-Coder-V2-Lite-Base"
    authorization: ""
    maxPrefixContext: 4096
    maxSuffixContext: 1024
    maxOutputToken: 300
    fimPrefix: "<｜fim▁begin｜>"
    fimMiddle: "<｜fim▁end｜>"
    fimSuffix: "<｜fim▁hole｜>"
    fimStop: ["<｜end▁of▁sentence｜>", "<|EOT|>", "▁<MID>"]
    tokenizerPath: "bin/cgtok/starcoder_tokenizer.json"
    timeout: 30000
  # - completionsUrl: "http://172.25.208.1:59999/v1/completions"
  #   modelName: "qwen"
  #   authorization: ""
  #   maxContext: 4096
  #   maxOutputToken: 1024
  #   fimPrefix: "<|fim_prefix|>"
  #   fimMiddle: "<|fim_middle|>"
  #   fimSuffix: "<|fim_suffix|>"
  #   fimStop: ["<|endoftext|>"]
  #   tokenizerPath: "bin/cgtok/starcoder_tokenizer.json"

# 补全配置
completionsConfig:
  disableScore: true
  disableLanguageFeature: false
  thresholdScore: 0.5
  strPattern: ".*"
  treePattern: ".*"
  lineCountThreshold: 100
  endTag: "</completion>"